Added Primary User ID to VerifyRes
FlowCrypt/flowcrypt-browser pull request #3258
Opened 2020-12-17 15:07 UTC by rrrooommmaaa

Closes #2147

2020-12-17 16:40 UTC, rrrooommmaaa commented
@tomholub Please have a look. We also have to keep in mind that uid might be absent

2020-12-17 17:51 UTC, tomholub requested changes
Looks good, with one potential change and one comment

2020-12-17 17:51 UTC, tomholub commented on extension/chrome/elements/pgp_block_modules/pgp-block-signature-module.ts
> +      const signerEmail = signature.signer?.primaryUserId ? Str.parseEmail(signature.signer.primaryUserId).email || this.view.senderEmail : this.view.senderEmail;
Should we remove the `this.view.senderEmail` here? And just stick to the signer, since sender can be spoofed.

2020-12-17 17:51 UTC, tomholub commented on extension/chrome/elements/pgp_block_modules/pgp-block-signature-module.ts
> +      const signerEmail = signature.signer?.primaryUserId ? Str.parseEmail(signature.signer.primaryUserId).email || this.view.senderEmail : this.view.senderEmail;
Then if it's not defined, use `(unknown signer)`

2020-12-17 17:51 UTC, tomholub commented on test/source/test.ts
> +  await ContactStore.save(undefined, contact);
Is it possible to put these lines somewhere closer to where they are being used?

2020-12-18 09:42 UTC, tomholub approved these changes

2020-12-18 11:08 UTC, rrrooommmaaa commented
@tomholub Looks like the "Unknown Signer" update affected "Fetched pubkey..." and "Missing pubkey..." messages.
Do we want to have "Unknown Signer" there?

2020-12-18 12:15 UTC, rrrooommmaaa commented
And SHA1 test also returns "Unknown Signer" because the signature isn't verified.

2020-12-18 12:32 UTC, tomholub commented
> @tomholub Looks like the "Unknown Signer" update affected "Fetched pubkey..." and "Missing pubkey..." messages.
Do we want to have "Unknown Signer" there?

If there is a missing pubkey, it should show clearly that it's missing pubkey as before (in the small text below). Since we only rely on the key uid.. and we don't have the key.. then indeed it should say `Unknown Signer` above the small text.

> "Fetched pubkey..." 

This is something we should fix - there's another issue for it https://github.com/FlowCrypt/flowcrypt-browser/issues/3105
If you think it's easier to fix in this PR, then you can do it, else you can do it in separate PR.

2020-12-18 12:33 UTC, tomholub commented
> And SHA1 test also returns "Unknown Signer" because the signature isn't verified.

That's probably ok. SHA1 is deprecated

2020-12-18 14:12 UTC, rrrooommmaaa commented
"Fetched pubkey..." and "Missing pubkey..." messages remain unchanged. It's the upper part changed (from sender e-mail to "Unknown Signer"). So I think we're good to merge it.

2020-12-18 14:31 UTC, tomholub approved these changes

2020-12-18 14:32 UTC, merged