Add optional reject callback to Catch.try
FlowCrypt/flowcrypt-browser pull request #3286
Opened 2021-01-03 20:58 UTC by rrrooommmaaa

Closes #2759 

Raising an exception inside 
```
       search.onsuccess = Catch.try(() => {
...
})
```
block resulted in unresolved Promise, so `const raw: unknown[] = await new Promise(...` hang.

2021-01-03 21:03 UTC, rrrooommmaaa commented
or perhaps, we shouldn't pass `reject` to `reportErr`, but make `Catch.try` a bit more complicated.

2021-01-03 21:11 UTC, tomholub commented on extension/js/common/platform/store/contact-store.ts
> +      }, reject);
I think better just stop using Catch.try in this situation. Instead put our own try/catch block inside the callback method here. Something like

```ts
search.onsuccess = () => {
  try {
    ...
  } catch(e) {
    reject(e)
  }
}
```

2021-01-03 21:11 UTC, tomholub commented on extension/js/common/platform/store/contact-store.ts
> +      }, reject);
Then Catch.try can stay as is.

Good find btw.

2021-01-04 13:24 UTC, tomholub requested changes
This looks good - assuming you have tested it to properly pass the error back to the caller.

Can you please do the same with all of the `search.onsuccess = ` in other methods? It seems the existing `Catch.try` will be swallowing up the errors (and reporting them) leaving the caller hanging.

2021-01-06 14:47 UTC, tomholub approved these changes

2021-01-06 14:48 UTC, merged