Fix images preview for Firefox
FlowCrypt/flowcrypt-browser pull request #3704
Opened 2021-05-29 20:12 UTC by limonte

This PR changes the way of showing images in attachment preview to use base64 src.

close #3707

----------------------------------

**Tests** _(delete all except exactly one)_:
- Difficult to test, we currently don't test in Firefox

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

2021-05-30 07:34 UTC, seisvelas requested changes
Related to the comment I left in https://github.com/FlowCrypt/flowcrypt-browser/issues/3703 (the issue this PR pertains to), I tested by adding `blob:` to the CSP in the manifest.json, and it fixed the issue - I could successfully load image previews in Firefox.

I think two changes should be made:

1. Add `blob:` to the `img-src` directive in the CSP
2. Remove the meta tag CSP (the sole directive it includes is already included in the extension's CSP, which overrides it in any case)

But it's very plausible I'm completely misunderstanding something, in which case please don't hesitate to correct me!

If you agree with these changes, though, do let me know and I can implement them right here in this PR.

2021-05-30 09:03 UTC, limonte commented
> Related to the comment I left in #3703 (the issue this PR pertains to), I tested by adding `blob:` to the CSP in the manifest.json, and it fixed the issue - I could successfully load image previews in Firefox.
> 
> I think two changes should be made:
> 
> 1. Add `blob:` to the `img-src` directive in the CSP
> 2. Remove the meta tag CSP (the sole directive it includes is already included in the extension's CSP, which overrides it in any case)
> 
> But it's very plausible I'm completely misunderstanding something, in which case please don't hesitate to correct me!
> 
> If you agree with these changes, though, do let me know and I can implement them right here in this PR.

@seisvelas thank you for looking into this! I'd like to see your solution, but please submit it in another PR. I'll be happy to close this one in favor of your approach.

2021-05-30 21:47 UTC, seisvelas commented
Sure! I've made a draft at https://github.com/FlowCrypt/flowcrypt-browser/pull/3706 showing my proposed changes. I'll also take some screenshots showing that this does indeed fix the issue for me (but a bit later today).

2021-05-30 22:24 UTC, limonte commented
Closing in favor of #3706 

Thank you @seisvelas!

2021-05-30 22:24 UTC, closed without merging

2021-05-31 05:27 UTC, seisvelas commented
No problem, glad I could help!