Issue 3952 improve text clarity with password protected email
FlowCrypt/flowcrypt-browser pull request #3953
Opened 2021-09-03 05:08 UTC by martgil

This PR will  improve text clarity with password-protected email

close #3952 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)
- Tests will be added later (issue #...)
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

2021-09-03 19:36 UTC, rrrooommmaaa requested changes

2021-09-06 08:44 UTC, martgil commented on extension/js/common/lang.ts
> +    msgEncryptedText: (lang: string, acctEmail: string) => lang === 'EN' ? `${acctEmail} has sent you a password-encrypted email. Follow this link to open it: ` : `${acctEmail} hat Ihnen eine passwor
Oh, yes! It should definitely work like that! I'll be working on it. Thank you sir!

2021-09-06 08:51 UTC, martgil commented on extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
> +    text.push(Lang.compose.msgEncryptedText(lang, Xss.escape(this.acctEmail)) + msgUrl + '\n\n');
Copy sir, @rrrooommmaaa. Thanks for the very helpful context here. I'll be working on this as soon as possible.

2021-09-08 10:39 UTC, martgil commented
sir, @rrrooommmaaa. I was able to follow your given instructions which found helpful as usual. When I tried to get combine it and try to read the sent email by email subject using 
```javascript
      const sentMsg = (await GoogleData.withInitializedData('flowcrypt.compatibility@gmail.com')).getMessageBySubject(subject)!;
```
From here I'm getting undefined as the returned value.  I found out that the function `getMessageBySubject` pulls some data from `AcctDataFile`? Is there any chance that I need to create another file in the project which contains a message and subject that matches the same subject that I'm including in this test? The specific subject that I'm using is 
```javascript
      const subject = 'PWD encrypted message with flowcrypt.com/api';
```
which was later could be use in `TestBySubjectStrategyContext`

Thanks in advance.

2021-09-08 14:26 UTC, rrrooommmaaa commented
Hi @martgil I think we don't need to extract the sent message like this.
Messages with a subject containing 'PWD encrypted message with flowcrypt.com/api' will go to `PwdEncryptedMessageWithFlowCryptComApiTestStrategy`. It doesn't save the message to DATA, like some other "strategies" do, like `SaveMessageInStorageStrategy`.
Other strategies just make some checks and possibly throw an exception, thus making the test fail.
It's enough to set breakpoint in the PwdEncryptedMessageWithFlowCryptComApiTestStrategy, make sure it is actually hit (I've already added a check to compare text with sender e-mail address there -- you should see if you pulled my update) and see if any exception is thrown there in all 3 tests. This is what I meant by 'verification happens in some other place' -- that is, we don't need to verify in the test body. We can verify in this strategy -- it has all the necessary input -- incoming e-mail with "From" and the text. We can simply leave a comment in the test body like Tom did:
```
      // this test is using PwdEncryptedMessageWithFlowCryptComApiTestStrategy to check sent result based on subject "PWD encrypted message with flowcrypt.com/api"
```

2021-09-09 05:08 UTC, martgil commented
Ah, you're right @rrrooommmaaa. I finally get it now :) Thank you so much!!

2021-09-09 10:58 UTC, rrrooommmaaa approved these changes

2021-09-09 11:00 UTC, merged