issue #4097 add warning when manually importing public keys
FlowCrypt/flowcrypt-browser pull request #4110
Opened 2021-11-10 16:32 UTC by limonte

This PR adds an orange warning when manually importing public keys. It also fixes the broken layout of `chrome/elements/pgp_pubkey.htm`

close #4097
close #4104

<img width="610" alt="CleanShot 2021-11-10 at 18 26 08@2x" src="https://user-images.githubusercontent.com/6059356/141153352-2926d6c9-73da-45fa-b080-98d5349eeab8.png">

<img width="797" alt="CleanShot 2021-11-10 at 18 24 26@2x" src="https://user-images.githubusercontent.com/6059356/141153426-c89a7e55-7212-4365-95d6-0a3b0f94d18f.png">

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

2021-11-11 10:55 UTC, rrrooommmaaa requested changes
The Bulk Import screenshot says "verify that the fingerprint matches" however, the fingerprint itself isn't displayed -- not very user-friendly.
Also, we have `add_pubkey.htm` dialog invoked from composer as I can see (example is demonstrated in `compose - settings - manually copied pubkey` test and some other tests). Apart from "Copy from Contact" options, there are also options to load from file or paste directly without any warnings whatsoever -- not even showing the email address inside the key/certificate. Perhaps, we should make use of `pgp_pubkey.htm` frame here somwehow -- file it in a separate issue?

2021-11-11 10:58 UTC, rrrooommmaaa commented
Actually, the "Copy from Contact" option is looking ugly -- I'm filing an issue for that too

2021-11-12 13:36 UTC, tomholub commented
Thank you for these observations.

Let's do the following in this PR:

> The Bulk Import screenshot says "verify that the fingerprint matches" however, the fingerprint itself isn't displayed -- not very user-friendly.

- [ ] Let's change the sentence in bulk import to: `Manually importing Public Keys can be dangerous`

> Also, we have `add_pubkey.htm` dialog invoked from composer as I can see (example is demonstrated in `compose - settings - manually copied pubkey` test and some other tests). Apart from "Copy from Contact" options, there are also options to load from file or paste directly without any warnings whatsoever

- [ ] `add_pubkey.htm` please add orange warning `Manually importing Public Keys can be dangerous`

Additionally in this PR:

- [ ] Please change the color of `Update Key` in `pgp_pubkey.htm` to orange
- [ ] similarly button color in bulk import to be orange
- [ ] the `OK` button in `add_pubkey.htm` also orange

That should cover it. Didn't notice this when writing the issue. Thanks!

2021-11-12 22:49 UTC, limonte commented
> * [ ]  Let's change the sentence in bulk import to: `Manually importing Public Keys can be dangerous`

Done: 

![CleanShot 2021-11-13 at 00 41 58@2x](https://user-images.githubusercontent.com/6059356/141570785-6e936ef8-cc93-48e8-a435-6ce2af9357ec.png)

> * [ ]  `add_pubkey.htm` please add orange warning `Manually importing Public Keys can be dangerous`

Done:

<img width="583" alt="CleanShot 2021-11-13 at 00 41 16@2x" src="https://user-images.githubusercontent.com/6059356/141571437-5b8ee879-2619-4435-a655-be24106d6570.png">

> * [ ]  Please change the color of `Update Key` in `pgp_pubkey.htm` to orange

Done:

<img width="583" alt="CleanShot 2021-11-13 at 00 40 59@2x" src="https://user-images.githubusercontent.com/6059356/141572223-95731a03-75ed-4225-83e5-59c7440e49ce.png">

> * [ ]  similarly button color in bulk import to be orange

Done, see screenshot above.

> * [ ]  the `OK` button in `add_pubkey.htm` also orange

Done, see screenshot above.

Thank you both for the detailed review and suggestions!

---

I personally have one UX concern. On both bulk import and `add_pubkey.htm` pages, we mention that "Manually importing Public Keys can be dangerous" without any further details answering "Why?" and "What to do about it?". Here's what GitHub co-pilot was suggesting:

<img width="536" alt="CleanShot 2021-11-13 at 00 28 17@2x" src="https://user-images.githubusercontent.com/6059356/141576051-add26c75-570c-4d1b-bee5-9814a4d0c2b0.png">

It would be indeed helpful to create a small page with the information about importing and link that page on bulk import and `add_pubkey.htm` pages.

2021-11-12 22:50 UTC, tomholub commented
Good idea about explaining it. I'll file an issue.

2021-11-12 22:56 UTC, limonte commented on extension/chrome/settings/modules/contacts.ts
> +        $('#bulk_import .input_pubkey, #bulk_import .action_process, #file_import, #fineuploader_button').css('display', 'none');
This is the fix for the unrelated issue when the unwanted block was shown after doing bulk import:

![CleanShot 2021-11-13 at 00 34 53@2x](https://user-images.githubusercontent.com/6059356/141585789-d755c1f5-e7e7-4a47-867d-c9587c44ed93.png)

2021-11-13 07:06 UTC, rrrooommmaaa approved these changes

2021-11-13 07:06 UTC, merged