issue #3905 Refactor to use ContactStore.getOneWithAllPubkeys() instead of .get()
FlowCrypt/flowcrypt-browser pull request #4317
Opened 2022-03-03 21:50 UTC by IvanPizhenko

This PR refactors code to use `ContactStore.getOneWithAllPubkeys()` instead of `ContactStore.get()`

close #3905 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

2022-03-08 22:43 UTC, IvanPizhenko commented
@rrrooommmaaa Ready for review

2022-03-09 19:08 UTC, rrrooommmaaa requested changes

2022-03-09 19:08 UTC, rrrooommmaaa commented on extension/js/content_scripts/webmail/gmail-element-replacer.ts
> +                  const contactWithPubKeys = await ContactStore.getOneWithAllPubkeys(undefined, email);
need to think this through. Should we try to lookup a pubkey if we only have a revoked version in the cache?...

2022-03-10 14:30 UTC, IvanPizhenko commented on extension/chrome/elements/compose-modules/compose-recipients-module.ts
> +        const contactWithPubKeys = await ContactStore.getOneWithAllPubkeys(undefined, recipient.email);
Not sure how to check this, but will try

2022-03-10 14:36 UTC, IvanPizhenko commented on extension/chrome/elements/compose-modules/compose-recipients-module.ts
> +        const contactWithPubKeys = await ContactStore.getOneWithAllPubkeys(undefined, recipient.email);
Seems like `getEncryptionKeys()` does all the stuff.

2022-03-10 14:56 UTC, IvanPizhenko commented
@rrrooommmaaa I've made some fixes. Please recheck.

2022-03-10 19:14 UTC, rrrooommmaaa commented on test/source/tests/browser-unit-tests/unit-ContactStore.js
> +  if (contactByEmail.sortedPubkeys[0].pubkey.id !== fingerprint) {
I have fixed this test

2022-03-12 17:14 UTC, IvanPizhenko commented
@rrrooommmaaa all tests have passed, so PR likely can be merged

2022-03-14 13:04 UTC, rrrooommmaaa approved these changes

2022-03-14 13:05 UTC, merged