#4740 Enable users to change reply option while compose
FlowCrypt/flowcrypt-browser pull request #4751
Opened 2022-10-20 07:49 UTC by ioanmo226

This PR enables users to change reply option while compose

close #4740 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

2022-10-21 07:14 UTC, ioanmo226 commented on test/source/mock/google/exported-messages/message-export-183ec175f060b2c2.json
> +{
@rrrooommmaaa FYI Need to review https://github.com/FlowCrypt/flowcrypt-browser/pull/4742 first

2022-10-21 13:24 UTC, ioanmo226 commented
![chrome-capture-2022-9-21](https://user-images.githubusercontent.com/77344191/197206307-b0e83243-2735-4649-a59a-8411da790709.gif)

2022-10-24 18:29 UTC, rrrooommmaaa requested changes
It looked good when I tested it.
There is one typo and a couple of tests that I think are missing.

2022-10-24 18:29 UTC, rrrooommmaaa commented on extension/chrome/elements/compose-modules/compose-render-module.ts
> +      this.view.recipientsModule.addRecipients(recipients, false).catch(Catch.reportErr);
We should use `this.view.replyParams` directly, as the new object still has references to the old object's arrays, and we would need to care about all the places they could be possibly modified.
`this.view.recipientsModule.addRecipients(this.view.replyParams, ...`

2022-10-24 18:29 UTC, rrrooommmaaa commented on extension/chrome/elements/compose-modules/compose-reply-btn-popover-module.ts
> +    a_reply_all: { text: 'Replay All', iconPath: '/img/reply-all-icon.png' },
There is a typo: Repl`a`y All

2022-10-24 18:29 UTC, rrrooommmaaa commented on test/source/tests/compose.ts
> +    }));
Why don't we test `@action-toggle-a_reply_all` while we're at it?

2022-10-24 19:03 UTC, rrrooommmaaa approved these changes

2022-10-24 19:52 UTC, merged